### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by ThibaultFeugere** [boringthegod/postmaniac#2]
When i launch postmaniac script from Github source code, I sometime get this error with this input at `Scan du workspace` step : `python3 postmaniac/postmaniac.py facebook`

Stack trace : 

```
Scan du workspace 11/85 [########################################]Traceback (most recent call last):
  File "/Users/Downloads/postmaniac/postmaniac/postmaniac.py", line 408, in <module>
    main()
  File "/Users/Downloads/postmaniac/postmaniac/postmaniac.py", line 144, in main
    worksp = match_workspace.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by boringthegod** [comment]
already fix in https://github.com/boringthegod/postmaniac/issues/1#issuecomment-1546655808
